### ISSUE TITLE
Suppose to work?

### ISSUE THREAD

**Issue by limelect** [HemulGM/VCLTaskBarToFMX#1]
D10.2.3
![Screenshot - 18_08_2022 , 17_31_38](https://user-images.githubusercontent.com/4199131/185421047-cb52671e-d1ad-41c2-8564-32837abe715f.jpg)

Does nothing

**Comment by HemulGM** [comment]
@limelect  Post an example

**Comment by limelect** [comment]
your example

**Comment by limelect** [comment]
unit Unit1;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, System.Win.TaskbarCore, Vcl.Taskbar;

type
  TForm1 = class(TForm)
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
     procedure FOnThumbClick(Sender: TObject; AButtonID: Integer);

  end;

var
  Form1: TForm1;
  FTaskBar : TTaskbar;

implementation

{$R *.dfm}
 uses HGM.TaskBar;

procedure TForm1.FormCreate(Sender: TObject);
begin
  FTaskBar := TTaskbar.Create(Self);
  FTaskBar.OnThumbButtonClick := FOnThumbClick;
  FTaskBar.ProgressState := TTaskBarProgressState.Normal;
  FTaskBar.ProgressMaxValue := 100;
  FTaskBar.ProgressValue := 32;
  FTaskBar.TaskBarButtons.BeginUpdate; //important (lock of update for buttons)
  try
   with FTaskBar.TaskBarButtons.Add do
   begin
     Icon.LoadFromFile('Dolphin.ico');
     Hint := '123';
   end;
  finally
    FTaskBar.TaskBarButtons.EndUpdate;

end;
end;

 procedure TForm1.FOnThumbClick(Sender: TObject; AButtonID: Integer);
begin
  ShowMessage(AButtonID.ToString);
end;
end.

**Comment by HemulGM** [comment]
@limelect This module is for the operation of TaskBar in FMX. In Vcl, and so regularly there is this component. There is no need to use this module.

**Comment by limelect** [comment]
Ok so you made a big mistake.
I first did an FMX project Delphi did not access it as it has VCL !!!!!
in your delphi source
So fix it then we can go on

**Comment by HemulGM** [comment]
@limelect It's not a mistake. I am using a component for VCL inside FMX. The VCL application does NOT need this module. It is only needed for FMX projects!

**Comment by limelect** [comment]
good luck
