### ISSUE TITLE
does nothing

### ISSUE THREAD

**Issue by limelect** [HemulGM/VCLTaskBarToFMX#2]
Out of curiosity, I made same VCL project as FMX project
Both do nothing
Do not bother to answer

**Comment by HemulGM** [comment]
*face palm*
@limelect  Do you understand what are saying to you?
This module is ONLY for FMX!
Create an FMX application, connect the module, create a class object according to the example. And you will see that it works as intended

**Comment by HemulGM** [comment]
Use an example if you don't understand
https://github.com/HemulGM/VCLTaskBarToFMX/tree/main/Sample

**Comment by limelect** [comment]
Stil does nothing >>>>>>>>>>> D10.2.3

It seems you do not agree with a professional of 30 years
