### ISSUE TITLE
Still does nothing

### ISSUE THREAD

**Issue by limelect** [HemulGM/VCLTaskBarToFMX#3]
Even with your demo does nothing

Stil does nothing >>>>>>>>>>> D10.2.3

It seems you do not agree with a professional of 30 years

**Comment by HemulGM** [comment]
You call yourself a professional, but at the same time you say that "nothing works"?
Are you seriously? No professional would say that. He will say what doesn't work and even why it might not work.

**Comment by limelect** [comment]
I will not debug your problem
Just trying to feedback results
I will not help anymore
So good luck

**Comment by limelect** [comment]
P.s just see my site maybe you can get some free stuff that work
www.limelect,com
